#!/bin/bash

# https://k3d.io/v5.4.9/
# example: k3d cluster create test --servers 1 --agents 2

set -E -o errexit -o nounset -o pipefail
curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
